class AddBlandsToProfiles < ActiveRecord::Migration
  def change
    add_column :profiles, :GNU, :boolean
    add_column :profiles, :libtech, :boolean
    add_column :profiles, :Omatic, :boolean
    add_column :profiles, :Stepchild, :boolean
    add_column :profiles, :Capita, :boolean
    add_column :profiles, :Neversummer, :boolean
    add_column :profiles, :K2, :boolean
    add_column :profiles, :ForumA, :boolean
    add_column :profiles, :Rome, :boolean
    add_column :profiles, :Lamar, :boolean
    add_column :profiles, :Morrow, :boolean
    add_column :profiles, :LTD, :boolean
    add_column :profiles, :Dragon, :boolean
    add_column :profiles, :Anon, :boolean
    add_column :profiles, :Flow, :boolean
    add_column :profiles, :Four_square, :boolean
    add_column :profiles, :Forum, :boolean
    add_column :profiles, :DC, :boolean
    add_column :profiles, :Dakine, :boolean
    add_column :profiles, :Grenade, :boolean
    add_column :profiles, :Celtek, :boolean
    add_column :profiles, :six_eight_six, :boolean
    add_column :profiles, :Airblaster, :boolean
    add_column :profiles, :Bonfire, :boolean
    add_column :profiles, :Electric, :boolean
    add_column :profiles, :Nike_Snowboarding, :boolean
    add_column :profiles, :RED, :boolean
    add_column :profiles, :Roxy, :boolean
    add_column :profiles, :Skullcandy, :boolean
    add_column :profiles, :Sessions, :boolean
    add_column :profiles, :Smith, :boolean
    add_column :profiles, :Special_Blend, :boolean
    add_column :profiles, :Thirty_two, :boolean
    add_column :profiles, :Union, :boolean
    add_column :profiles, :bentmetal, :boolean
    add_column :profiles, :Volcom, :boolean
    add_column :profiles, :Vans, :boolean
    add_column :profiles, :Salomon, :boolean
    add_column :profiles, :One_Ball_Jay, :boolean
    add_column :profiles, :Nomis, :boolean
    add_column :profiles, :Billa_Bong, :boolean
    add_column :profiles, :five_one_five_zero, :boolean
    add_column :profiles, :Analog, :boolean
    add_column :profiles, :Avalanche, :boolean
    add_column :profiles, :Drake, :boolean
    add_column :profiles, :Element, :boolean
    add_column :profiles, :Limited, :boolean
    add_column :profiles, :Palmer_Snowboards, :boolean
    add_column :profiles, :Quiksilver, :boolean
    add_column :profiles, :Rossignol, :boolean
    add_column :profiles, :Spyder, :boolean
    add_column :profiles, :Technine, :boolean
    add_column :profiles, :Swix, :boolean
    add_column :profiles, :The_North_Face, :boolean
  end
end
